var regAcct=document.querySelector("#reg-acct"),builder=document.querySelector("#builder"),ruby=document.querySelector("#ruby"),saphire=document.querySelector("#saphire"),emerald=document.querySelector("#emerald"),diamond=document.querySelector("#diamond"),crownDiamond=document.querySelector("#crown-diamond"),ambassador=document.querySelector("#ambassador"),crownAmbassador=document.querySelector("#crown-ambassador");function matrixPower(a){y=a-1;return Math.pow(2,y)}var submitConverter=document.querySelector("#submit-conv");
function submitConverterCalculator(){var a=document.querySelector("#quantities"),b=document.querySelector("#quantity1"),c=document.querySelector("#quantity2"),d=document.querySelector("#no-acct");"usd-ngn"==a.value&&(0<c.value.length?(b.value=400*parseFloat(c.value),d.value=Math.floor(parseFloat(c.value)/12)+" rem $"+parseFloat(c.value)%12):0<b.value.length?(c.value=parseFloat(b.value)/400,d.value=Math.floor(parseFloat(c.value)/12)+" rem $"+parseFloat(c.value)%12):0<d.value.length&&(c.value=12*Number(d.value),
b.value=400*parseFloat(c.value)))}var resetConverter=document.querySelector("#reset-conv");function resetConverterCalculator(){document.querySelector("#quantities");var a=document.querySelector("#quantity1"),b=document.querySelector("#quantity2"),c=document.querySelector("#no-acct");a.value="";b.value="";c.value=""}
var isQuantity1Valid=function(a){0<quantity1.value.length&&13===a.which&&submitConverterCalculator()},isQuantity2Valid=function(a){0<quantity2.value.length&&13===a.which&&submitConverterCalculator()},isQuantityValid=function(a){27===a.which&&resetConverterCalculator()};submitConverter.addEventListener("click",submitConverterCalculator);resetConverter.addEventListener("click",resetConverterCalculator);quantity1.addEventListener("keypress",isQuantity1Valid);quantity2.addEventListener("keypress",isQuantity2Valid);
quantity1.addEventListener("keypress",isQuantityValid);quantity2.addEventListener("keypress",isQuantityValid);
function basicCalculator(){var a=document.querySelector("#num1"),b=document.querySelector("#num2"),c=document.querySelector("#sign"),d=document.querySelector("#result-bas"),e=[];if(0<a.value.length&&0<b.value.length&&"+"==c.value)d.value=parseFloat(a.value)+parseFloat(b.value);else if(0<a.value.length&&0<b.value.length&&"-"==c.value)d.value=parseFloat(a.value)-parseFloat(b.value);else if(0<a.value.length&&0<b.value.length&&"*"==c.value)d.value=parseFloat(a.value)*b.value;else if(0<a.value.length&&
0<b.value.length&&"/"==c.value)d.value=parseFloat(a.value)/parseFloat(b.value);else if(0<a.value.length&&0<b.value.length&&"power"==c.value)d.value=Math.pow(parseFloat(a.value),parseFloat(b.value));else if(0<a.value.length&&0<b.value.length&&"modulus"==c.value)d.value=Math.floor(parseFloat(a.value)/parseFloat(b.value))+" rem "+parseFloat(a.value)%parseFloat(b.value);else if(0<a.value.length&&0<b.value.length&&"power"==c.value)d.value=Math.pow(a.value,b.value);else if(0<a.value.length&&0<b.value.length&&
"tot-pow"==c.value)for(a=0;a<=b.value;a++)e.push(Math.pow(2,a)),d.value=e.reduce(function(f,g){return f+g},0);else"select operator"==c.value?alert("Syntax Error"):alert("Math Error!"),d.value=""}function resetCalculator(){var a=document.querySelector("#num1"),b=document.querySelector("#num2"),c=document.querySelector("#sign"),d=document.querySelector("#result-bas");a.value="";b.value="";d.value="";c.value=document.querySelector("#sign-option").value}
var isNum1Valid=function(a){0<num1.value.length&&13===a.which&&basicCalculator()},isNum2Valid=function(a){0<num2.value.length&&13===a.which&&basicCalculator()},submitBasic=document.querySelector("#submit-bas"),resetBasic=document.querySelector("#reset-bas");submitBasic.addEventListener("click",basicCalculator);resetBasic.addEventListener("click",resetCalculator);num1.addEventListener("keypress",isNum1Valid);num2.addEventListener("keypress",isNum2Valid);
function checkAmbassador(){if(15<=ambassador.value){for(var a=[],b=14;b<ambassador.value;b+=8)a.push(b);var c=0;a.forEach(function(d){return c+=1});crownAmbassador.value=parseInt(c);ambassador.value=parseInt(ambassador.value)-parseInt(crownAmbassador.value);crownDiamond.value=parseInt(crownDiamond.value)-parseInt(ambassador.value)-parseInt(crownAmbassador.value);diamond.value=parseInt(diamond.value)-parseInt(crownDiamond.value)-parseInt(ambassador.value)-parseInt(crownAmbassador.value);emerald.value=
parseInt(emerald.value)-parseInt(diamond.value)-parseInt(crownDiamond.value)-parseInt(ambassador.value)-parseInt(crownAmbassador.value);ruby.value=parseInt(ruby.value)-parseInt(emerald.value)-parseInt(diamond.value)-parseInt(crownDiamond.value)-parseInt(ambassador.value)-parseInt(crownAmbassador.value);saphire.value=parseInt(saphire.value)-parseInt(ruby.value)-parseInt(emerald.value)-parseInt(diamond.value)-parseInt(crownDiamond.value)-parseInt(ambassador.value)-parseInt(crownAmbassador.value);builder.value=
parseInt(regAcct.value)-parseInt(saphire.value)-parseInt(ruby.value)-parseInt(emerald.value)-parseInt(diamond.value)-parseInt(crownDiamond.value)-parseInt(ambassador.value)-parseInt(crownAmbassador.value)}}
function checkCrownDiamond(){if(15<=crownDiamond.value){for(var a=[],b=14;b<crownDiamond.value;b+=8)a.push(b);var c=0;a.forEach(function(d){return c+=1});ambassador.value=parseInt(c);crownDiamond.value=parseInt(crownDiamond.value)-parseInt(ambassador.value);emerald.value=parseInt(emerald.value)-parseInt(crownDiamond.value)-parseInt(ambassador.value);ruby.value=parseInt(ruby.value)-parseInt(emerald.value)-parseInt(crownDiamond.value)-parseInt(ambassador.value);saphire.value=parseInt(saphire.value)-
parseInt(ruby.value)-parseInt(emerald.value)-parseInt(crownDiamond.value)-parseInt(ambassador.value);builder.value=parseInt(regAcct.value)-parseInt(saphire.value)-parseInt(ruby.value)-parseInt(emerald.value)-parseInt(crownDiamond.value)-parseInt(ambassador.value);crownAmbassador.value=""}}
function checkDiamond(){if(15<=diamond.value){for(var a=[],b=14;b<diamond.value;b+=8)a.push(b);var c=0;a.forEach(function(d){return c+=1});crownDiamond.value=parseInt(c);diamond.value=parseInt(diamond.value)-parseInt(crownDiamond.value);emerald.value=parseInt(emerald.value)-parseInt(diamond.value)-parseInt(crownDiamond.value);ruby.value=parseInt(ruby.value)-parseInt(emerald.value)-parseInt(diamond.value)-parseInt(crownDiamond.value);saphire.value=parseInt(saphire.value)-parseInt(ruby.value)-parseInt(emerald.value)-
parseInt(diamond.value)-parseInt(crownDiamond.value);builder.value=parseInt(regAcct.value)-parseInt(saphire.value)-parseInt(ruby.value)-parseInt(emerald.value)-parseInt(diamond.value)-parseInt(crownDiamond.value);ambassador.value="";crownAmbassador.value=""}}
function checkEmerald(){if(15<=emerald.value){for(var a=[],b=14;b<emerald.value;b+=8)a.push(b);var c=0;a.forEach(function(d){return c+=1});diamond.value=parseInt(c);emerald.value=parseFloat(emerald.value)-parseFloat(diamond.value);ruby.value=parseInt(ruby.value)-parseInt(emerald.value)-parseInt(diamond.value);saphire.value=parseInt(saphire.value)-parseInt(ruby.value)-parseInt(emerald.value)-parseInt(diamond.value);builder.value=parseInt(regAcct.value)-parseInt(saphire.value)-parseInt(ruby.value)-
parseInt(emerald.value)-parseInt(diamond.value);ambassador.value="";crownAmbassador.value="";crownDiamond.value=""}}
function checkRuby(){if(15<=ruby.value){for(var a=[],b=14;b<ruby.value;b+=8)a.push(b);var c=0;a.forEach(function(d){return c+=1});emerald.value=parseInt(c);ruby.value=parseInt(ruby.value)-parseInt(emerald.value);saphire.value=parseInt(saphire.value)-parseInt(ruby.value)-parseInt(emerald.value);builder.value=parseInt(regAcct.value)-parseInt(saphire.value)-parseInt(ruby.value)-parseInt(emerald.value);ambassador.value="";crownAmbassador.value="";crownDiamond.value="";diamond.value=""}}
function checkSaphire(){if(15<=saphire.value){for(var a=document.querySelector("#reg-acct"),b=[],c=14;c<saphire.value;c+=8)b.push(c);var d=0;b.forEach(function(e){return d+=1});ruby.value=parseInt(d);saphire.value=parseInt(saphire.value)-parseInt(ruby.value);builder.value=parseInt(a.value)-parseInt(saphire.value)-parseInt(ruby.value);ambassador.value="";crownAmbassador.value="";crownDiamond.value="";diamond.value="";emerald.value=""}}
function checkRegisteredAcct(){if(7>regAcct.value)builder.value=regAcct.value;else if(7<=regAcct.value){for(var a=[],b=6;b<regAcct.value;b+=4)a.push(b);var c=0;a.forEach(function(d){return c+=1});saphire.value=parseInt(c);builder.value=parseInt(regAcct.value)-parseInt(saphire.value);ambassador.value="";crownAmbassador.value="";crownDiamond.value="";diamond.value="";emerald.value="";ruby.value=""}}
function matrixCalculator(){checkRegisteredAcct();checkSaphire();checkRuby();checkEmerald();checkDiamond();checkCrownDiamond();checkAmbassador()}
function resetMatrixCalculator(){var a=document.querySelector("#reg-acct"),b=document.querySelector("#builder"),c=document.querySelector("#ruby"),d=document.querySelector("#saphire"),e=document.querySelector("#emerald"),f=document.querySelector("#diamond"),g=document.querySelector("#crown-diamond"),h=document.querySelector("#ambassador"),k=document.querySelector("#crown-ambassador");a.value="";b.value="";c.value="";d.value="";e.value="";f.value="";g.value="";h.value="";k.value=""}
var submitMatrix=document.querySelector("#submit-mat"),resetMatrix=document.querySelector("#reset-mat"),isKeyValid=function(a){0<regAcct.value.length&&13===a.which&&matrixCalculator()};submitMatrix.addEventListener("click",matrixCalculator);resetMatrix.addEventListener("click",resetMatrixCalculator);regAcct.addEventListener("keypress",isKeyValid);